### ISSUE TITLE
Custom Accent Colours doesn't show up as an option under Shell Theme in Tweak

### ISSUE THREAD

**Issue by disisdrsid** [dimitriskp22/custom-accent-colors#16]
Love the extension, but clearly I'm missing a step in getting it to work.. I've installed CustomAccentColours from the extensions.gnome.org website and I'm using the User Themes extension from the Fedora repos, and I have rebooted a couple times but CAC is not available as an option under Shell Themes

Distro: Fedora 38 running GNOME 44.2 under Wayland

I didn't know which pictures, if any to add, please let me know and I will add them

Thanks in advance for the help, and again, really really like the extension's concept!

**Comment by dimitriskp22** [comment]
the shell theming feature of the extension is not enabled by default, have you enabled the Shell Theming option in the extension settings?

**Comment by disisdrsid** [comment]
> the shell theming feature of the extension is not enabled by default, have you enabled the Shell Theming option in the extension settings?

Yes it is enabled, I can import a third party theme from elsewhere and use it. 
I tried downloading the latest release of CAC from here, but it defaults colours to yellow with no option to change it

**Comment by dimitriskp22** [comment]
how did you installed the extension on your system? I just installed the extension using the extension manager app on a fedora 38 virtual machine and it seems to be working as intended.

**Comment by disisdrsid** [comment]
I used the webpage to get CAC and used the repos to get User Themes

**Comment by disisdrsid** [comment]
Can I manually create the folder in ~/themes and add the files there? I'm not 100% sure what I'd do for a _shell_ theme

**Comment by dimitriskp22** [comment]
this is where the shell themes go too (or in ~/.local/share/themes)

**Comment by disisdrsid** [comment]
I only have one user on my partition, so the home folder should work, could you tell me what files I'd need to add there?

**Comment by disisdrsid** [comment]
I only have one user on my partition, so the home folder should work, could you tell me what files I'd need to add there?

**Comment by dimitriskp22** [comment]
maybe you could try to remove the cac extension, re-login, and then install the extension manager app and install the cac extension using this app

**Comment by disisdrsid** [comment]
Let me try that out, one moment

**Comment by disisdrsid** [comment]
> maybe you could try to remove the cac extension, re-login, and then install the extension manager app and install the cac extension using this app

No luck I'm afraid, still not detected

**Comment by dimitriskp22** [comment]
can you sent a screenshot of the gnome tweaks appearance page and the settings page of the extension?

**Comment by disisdrsid** [comment]
![Screenshot from 2023-06-18 14-25-38](https://github.com/dimitriskp22/custom-accent-colors/assets/28841157/5b2ad8dd-6ac5-48e8-a40a-9223aeac3e47)
![Screenshot from 2023-06-18 14-26-31](https://github.com/dimitriskp22/custom-accent-colors/assets/28841157/19a25923-627f-4261-b6c2-5511c8cc520c)

**Comment by dimitriskp22** [comment]
maybe try to turn off shell theming and enabling it again, and then relogin, if that doesn't work maybe there's a problem with your system, since the extension works on a freshly installed fedora 38 virtual machine...a workaround I can think is to turn off the shell theming option, create a directory like this ~/.themes/custom-accent-colors/gnome-shell and copy the gnome-shell.css file with the color you want in there

**Comment by disisdrsid** [comment]
Thanks so much for the help, I'll consider doing that, or if I notice any more weird errors like that, I'll do a reinstall, and start again from scratch. 

I think I'll close the bug for now?
