### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yochananmarqos** [dimitriskp22/custom-accent-colors#19]
There are breaking changes which will require a separate release for 45 and <=44:

See https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by dimitriskp22** [comment]
Thank you for letting me know, I've taken a look in the gjs documentation and supporting gnome 45 doesn't seem too hard, I'll probably take care of it after I return from my vacation.

**Comment by dimitriskp22** [comment]
@KCGD I already have a Version of the Extension that works in Gnome OS with Gnome 45 but the Settings Panel is not yet ported. It's probably going to be released before Gnome 45 lands in Arch and Fedora.

**Comment by dtcooper** [comment]
Hello! Bumping since GNOME 45 has landed in Arch. Cheers and thanks. :)

**Comment by yochananmarqos** [comment]
@dtcooper It's already done in the main branch and working fine. My guess is the developer is waiting for approval on the extensions website.

**Comment by dimitriskp22** [comment]
@dtcooper I still have to compile the Gnome Shell themes for Gnome 45 and test if everything works properly, it's not a lot of work so if everything goes as planed I'll upload the new version on the extensions website this week.

**Comment by yochananmarqos** [comment]
@dimitriskp22 You forgot something: #21 :wink:
