### ISSUE TITLE
Some colors are not changing

### ISSUE THREAD

**Issue by Revanee** [dimitriskp22/custom-accent-colors#25]
Some accent colors (quick settings, calendar, maybe others) are not changing when using the extension

![Screenshot from 2023-11-14 20-12-26](https://github.com/dimitriskp22/custom-accent-colors/assets/10546877/0bbabdcc-9d3f-43c5-b52b-127dc0dd7d7f)

GNOME Shell 45.1

**Comment by dimitriskp22** [comment]
hey @Revanee , have you set the Shell Theme to Custom-Accent-Colors with Gnome Tweaks?

**Comment by Revanee** [comment]
Nope. I set it now and it works great! I don't see it mentioned in the README though.
