### ISSUE TITLE
Color does not change at all in Gnome 45.1

### ISSUE THREAD

**Issue by D1Ck3n** [dimitriskp22/custom-accent-colors#26]
Good day,

since Manjaro has updated to Gnome 45.1 i have this ugly blue accent color in my shell.

i tried your extension but it seems that the color does not change :/

Any hint for me?

**Comment by dimitriskp22** [comment]
hey @D1Ck3n , have you set the Shell Theme to Custom-Accent-Colors with Gnome Tweaks?

**Comment by D1Ck3n** [comment]
> hey @D1Ck3n , have you set the Shell Theme to Custom-Accent-Colors with Gnome Tweaks?

Hey @dimitriskp22 that fixed it, thanks! :)
