### ISSUE TITLE
Does not customize colors in control center

### ISSUE THREAD

**Issue by jasursadikov** [dimitriskp22/custom-accent-colors#28]
Unfortunately my control center is still default blue while all toggles are green now.

![image](https://github.com/dimitriskp22/custom-accent-colors/assets/14846427/b92464ea-b3e4-42c0-a880-de9c12312272)

**Comment by dimitriskp22** [comment]
hey @jasursadikov , have you set the Shell Theme to Custom-Accent-Colors with Gnome Tweaks?

**Comment by jasursadikov** [comment]
![image](https://github.com/dimitriskp22/custom-accent-colors/assets/14846427/9c699680-fa4a-456d-b59b-559e7b865fec)
@dimitriskp22 this appears to be as above. I am not really sure how to change that tbh.

**Comment by dimitriskp22** [comment]
you need to install and enable the user themes extension, then you'll be able to change the shell theme to Custom-Accent-Colors

**Comment by jasursadikov** [comment]
It worked, thanks! Please mention that in the repo's requirements!
