### ISSUE TITLE
Default Blue color not working as of last update

### ISSUE THREAD

**Issue by Anduril97** [dimitriskp22/custom-accent-colors#9]
Hey! As of the last update, when Blue (default) is chosen in this extension, the Custom-Accent-Colors menu option is not showing up in the Tweaks Shell Appearance dropdown anymore. Oddly, the extension works properly with any other color than the blue one. System: Manjaro Gnome (latest update).

**Comment by demiskp** [comment]
hey, since the latest update, the Blue (Default) option is basically a placeholder for the default adwaita, so when Blue (Default) is selected it removes all the custom gtk.css files and shell themes.

**Comment by Anduril97** [comment]
Ah I see! Any you could add a Blue option like the other colors as it was probably one of the best color options? Thanks for all your work on this

**Comment by demiskp** [comment]
I'll consider it for the next versions

**Comment by demiskp** [comment]
@naegling that's a great idea! I'll probably include it in v6 (along with gnome 44 support)
